### PR TITLE
[WIP] operator: regenerate client

### PR DESCRIPTION
**Pull request by bonifaido**
The client code was removed in an earlier PR and hasn't been regenerated.

Addresses: https://github.com/banzaicloud/bank-vaults/commit/15b29d0777f97ae916f4c840a769c93eda194718#commitcomment-33195416

### CODE REVIEW

File: operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+)
+
+// VaultSpecsGetter has a method to return a VaultSpecInterface.
+// A group's client should implement this interface.
+type VaultSpecsGetter interface {
+	VaultSpecs(namespace string) VaultSpecInterface
+}
+
+// VaultSpecInterface has methods to work with VaultSpec resources.
+type VaultSpecInterface interface {
```
Comment (ccojocar) [inline operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: It seems that the client was generated for `VaultSpec` instead of Vault.

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I think, the following directives need to be defined on `Vault` type:

```
// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
```

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I would try to remove the blank lines between the directives, and move the comment above them.

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: @bonifaido This work for me on vault:

```
// Vault represents a Vault Kubernetes object

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type Vault struct {
	metav1.TypeMeta `json:",inline"`
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec              VaultSpec   `json:"spec"`
	Status            VaultStatus `json:"status,omitempty"`
}

// VaultList represents a list of Vault Kubernetes objects
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type VaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []Vault `json:"items"`
}

```

Comment (bonifaido) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: Which generator version are you using?

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I works with both version `kuberntetes-1.14.1` or `kubernetes-1.11.3`.

Comment (bonifaido) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I sill get somehow compilation errors after the code is generated with `kubernetes/code-generator`:

```
# github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/scheme
operator/pkg/client/clientset/versioned/scheme/register.go:31:2: undefined: v1alpha1.AddToScheme
# github.com/banzaicloud/bank-vaults/operator/pkg/client/listers/vault/v1alpha1
operator/pkg/client/listers/vault/v1alpha1/vault.go:88:34: undefined: v1alpha1.Resource
```

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I think, you need to fix the type definition. There is a version here which compiles https://github.com/ccojocar/bank-vaults/commit/09a8641d30dba6e02f1ff248ca2399ef0c897468

Comment (bonifaido) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: Could you please submit a PR from this branch? If you made it work :) It would be greatl!

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: I have some compilation issue when I trying to use the client module:
```
# k8s.io/client-go/plugin/pkg/client/auth/azure
../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:246:4: cannot use expiresIn (type string) as type json.Number in field value
../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use expiresOn (type string) as type json.Number in field value
../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use expiresOn (type string) as type json.Number in field value
../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:265:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
../../../../pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/plugin/pkg/client/auth/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
# k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake
../../../../pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190308081736-3a66ae4d2f93/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_customresourcedefinition.go:126:48: too many arguments in call to testing.NewRootPatchSubresourceAction
        have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
        want (schema.GroupVersionResource, string, []byte, ...string)
make: *** [build] Error 2
```

I think `github.com/hashicorp/vault-plugin-auth-azure v0.0.0-20190201222632-0af1d040b5b3/go.mod h1:f+VmjSQIxxO+YTeO3FbPWRPCPbd3f3lwpP6jaO/YduQ=` is pulling an incomparable version of github.com/Azure/azure-sdk-for-go v23.2.0+incompatible/go.mod h1:9XXNKU+eRnpl9moKnB4QOLf1HestfXbmab5FXxiDBjc=`

Comment (bonifaido) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: We can try pulling in the compatible version, we have no preference here.

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: @bonifaido I am able to import successfully the client generated in this branch https://github.com/ccojocar/bank-vaults/commits/vop-client. I had to update the client-go.

Are you planning to take over the changes, or should I send you a PR?

Comment (bonifaido) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: If you have a working version in a branch I think it worth to send a PR, so we don't have to duplicate efforts, and it is possible that I would leave out something that would be useful for you. So please submit that branch in PR. Thank you very much!

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: OK. I will! Thanks

Comment (ccojocar) [reply operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultspec.go]: https://github.com/banzaicloud/bank-vaults/pull/428
